// "use client"
import { Inter } from "next/font/google";
import "./globals.css";
// import { Providers } from "./redux/provider";
import '../app/style/variables.module.scss'
import { AuthProvider } from "./hooks/contexts/AuthContext";
import { ThemeProvider } from "./hooks/contexts/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "react js ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <ThemeProvider>
  
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
      </ThemeProvider>
     </AuthProvider>
  );
}
